# container-based build
sudo: false

language: scala

env:
  - JAVA_OPTS="-Xmx4G -DSKIP_FLAKY=1"
  - PROJECT=finagle-commons-stats
  - PROJECT=finagle-cacheresolver
  - PROJECT=finagle-core
  - PROJECT=finagle-exception
  - PROJECT=finagle-exp
  - PROJECT=finagle-http
  - PROJECT=finagle-http-compat
  - PROJECT=finagle-netty4-http
  - PROJECT=finagle-http2
  - PROJECT=finagle-integration
  - PROJECT=finagle-kestrel
  - PROJECT=finagle-mdns
  - PROJECT=finagle-mux
  - PROJECT=finagle-mysql
  - PROJECT=finagle-netty4
  - PROJECT=finagle-ostrich4
  - PROJECT=finagle-redis
  - PROJECT=finagle-serversets
  - PROJECT=finagle-spdy
  - PROJECT=finagle-stats
  - PROJECT=finagle-stream
  # These targets are currently failing for known limitations in scrooge-plugin
  # - PROJECT=finagle-thrift
  # - PROJECT=finagle-thriftmux

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.m2
   - $HOME/.ivy2
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
   - $HOME/.gitshas

scala:
  - 2.11.8

jdk:
  - oraclejdk8

notifications:
  hipchat:
    rooms:
      secure: UlvjA1u/K7a/ykVt9hfRksqI5coq9k5fFqpeGCcEmqPOyrkOnCLj21xHHB16SzUfwy3pqjVK+B8kWORB9zaNyalHZm6I11Ba1hfmPXWemH/qA972IN/hdAQxnMVhhnWqJPzuoVlW7WAFxwltPTbAwDMzIczmsyMv+rCc2Xffiks=

before_script:
  # default $SBT_OPTS is irrelevant to sbt lancher
  - unset SBT_OPTS
  - mkdir -p $HOME/.gitshas
  - env GIT_SHA_DIR=$HOME/.gitshas ./bin/travisci
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION ci:update finagle-memcached/update
  - >
    if [[ "$TRAVIS_JDK_VERSION" = oraclejdk* ]]; then
      ./sbt ++$TRAVIS_SCALA_VERSION finagle-native/update
    fi

script:
  # don't test these projects because they don't pass on travis-ci
  - ./sbt ++$TRAVIS_SCALA_VERSION finagle-memcached/test:compile

  # run conditionally because they don't pass with openjdks
  - >
    if [[ "$TRAVIS_JDK_VERSION" = oraclejdk* ]]; then
      ./sbt ++$TRAVIS_SCALA_VERSION coverage finagle-native/test;
    fi

  # run for all environments
  - ./sbt ++$TRAVIS_SCALA_VERSION coverage $PROJECT/test coverageReport

after_success: 
  - ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - bash <(curl -s https://codecov.io/bash)
